main:
  - name: Home
    url: ""
    weight: 1
  - name: Practice Areas
    url: "#service"
    weight: 2
  - name: About
    url: "#about"
    weight: 3
  - name: Testimonials
    url: "#testimonial"
    weight: 4
sitemap:
  - name: Home
    url: ""
    weight: 1
  - name: Contact Us
    url: "contact"
    weight: 2
  - name: Products
    url: "product"
    weight: 3
